### ISSUE TITLE
file too big for single read

### ISSUE THREAD

**Issue by pfrenkiel** [marxjohnson/AutoHandbrake#1]
I run the following command

autohb.rb --file myfile.iso -o myfile 
I get:

autohb.rb:122 :in `read': file too big for single read (IOError)

**Comment by marxjohnson** [comment]
How big is myfile.iso?  Can you give me some more details about your environment, particularly the OS and ruby versions you're running?

**Comment by pfrenkiel** [comment]
On Tue, 24 Feb 2015, Mark Johnson wrote:

> How big is myfile.iso? Can you give me some more details about your environment, particularly the OS and ruby
> versions you're running?

   hi Mark,
   thank you for answering my post. Here are the requested informations:
   OS: Debian Jessie
   ruby 2.1.5p273 (2014-11-13) [i386-linux-gnu]
   Can the problem come from the gems I downloaded?
   I tried with several iso files of increasing sizes. Here are the results:

808M 
autohb.rb:168:in `split': invalid byte sequence in UTF-8 (ArgumentError)
         from /home/frenkiel/bin/autohb.rb:168:in`block in parse_output'
         from /home/frenkiel/bin/autohb.rb:160:in `each_line'
         from /home/frenkiel/bin/autohb.rb:160:in`parse_output'
         from /home/frenkiel/bin/autohb.rb:472:in `main'
         from /home/frenkiel/bin/autohb.rb:658:in`<main>'

1.7G 
autohb.rb:122:in `read': failed to allocate memory (NoMemoryError)
         from /home/frenkiel/bin/autohb.rb:122:in`scan_disc'
         from /home/frenkiel/bin/autohb.rb:471:in `main'
         from /home/frenkiel/bin/autohb.rb:658:in`<main>'

2.2G 
autohb.rb:122:in `read': file too big for single read (IOError)
         from /home/frenkiel/bin/autohb.rb:122:in`scan_disc'
         from /home/frenkiel/bin/autohb.rb:471:in `main'
         from /home/frenkiel/bin/autohb.rb:658:in`<main>'

As what I wanted seemed rather simple (get automatically french audio and sub-titles),
I also did some tests with a simple shell script like:
  HandBrakeCLI -i $IN -o $OUT \
    --native-language fre --native-dub \
    --custom-anamorphic --keep-display-aspect \
    --subtitle-burned $SB
    --subtitle $S \
    --subtitle-default $SD \
    --srt-default $SRT \
    -e x264 --x264-preset fast --x264-tune film \
    -scan \
    -m -t $T

but no parameter combination gave me the expected result.
for the sub-titles (no problem with audio)

## best regards,

Pierre Frenkiel

**Comment by marxjohnson** [comment]
Thanks Pierre, that's some really useful info.
I've not got time to look into this right now, but I'll try and take a look at it over the next couple of weeks.
